version: "3.9"
networks:
  text_network:
    driver: bridge
services:
  text_db:
    image: svgcant2022/text-ms:text_data_db
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - CONTAINER_NAME=Source_Text_Data_db
      #- NETWORK=text_network
    networks: 
      - text_network

  # text_ner:

  # text_sum:

  neo4j-graph:
    image: "neo4j:5.3.0-community"
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["graph-data-science"]
    networks: 
      - text_network
  # app:
  #   build: .
  #   container_name: controller
  #   restart: always
  #   command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "127.0.0.1:8000:8000"
  #   depends_on:
  #     - graph