version: "3.9"
networks:
  text_network:
    driver: bridge
services:
  text_db:
    image: svgcant2022/text-ms:text_data_db
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - CONTAINER_NAME=Source_Text_Data_db
      #- NETWORK=text_network
    networks: 
      - text_network

  text_ner:
    image: svgcant2022/text-ms:text_ner
    restart: unless-stopped
    ports:
      - "4080:4080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - CONTAINER_NAME=text_ner
      #- NETWORK=text_network
    networks: 
      - text_network
    depends_on:
      - text_db
      - neo4j-graph
      - controller

  # text_sum:

  neo4j-graph:
    image: "neo4j:5.3.0-community"
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["graph-data-science"]
    networks: 
      - text_network
  controller:
    image: svgcant2022/text-ms:text_controller
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - text_network
    depends_on:
      - neo4j-graph
      - text_db

# use docker-compose pull && docker-compose up -d to update the images
