version: "3.9"
networks:
  text_data:
    external: true
volumes:
  text_data_vol:
    external: true
  text_data_logs:
    external: true
services:
  neo4j-graph:
    image: "neo4j:5.3.0-community"
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - text_data_vol:/data
      - text_data_logs:/logs
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["graph-data-science"]
    networks: 
      - text_data
  controller:
    # image: svgcant2022/text-ms:text_controller
    image: text_controller
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - text_data_vol:/app/data
      - text_data_logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - text_data
    depends_on:
      - neo4j-graph

# use docker-compose pull && docker-compose up -d to update the images
